name: mobile_developer_test
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Util
  flutter_native_splash: ^2.4.1
  go_router: ^14.3.0
  flutter_screenutil: ^5.9.3
  logger: ^2.4.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  intl: ^0.19.0
  path: ^1.9.0

  # Connectivity
  connectivity_plus: ^6.0.5
  internet_connection_checker_plus: ^2.5.2
  open_settings_plus: ^0.3.3
  airplane_mode_checker: ^3.1.0

  # UI
  skeletonizer: ^1.4.2
  flutter_staggered_grid_view: ^0.7.0

  # Models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  equatable: ^2.0.5

  # Network
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  
  # Database
  sqflite: ^2.3.3+2
  shared_preferences: ^2.3.2

  # state management
  flutter_bloc: ^8.1.6

  # Dependency injection
  get_it: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner: 
  flutter_gen_runner:
  freezed:
  json_serializable:

flutter_gen:
  output: lib/generated
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/lottie/
    - assets/json/

  fonts:
    - family: Abhaya Libre ExtraBold
      fonts:
        - asset: assets/fonts/AbhayaLibre-Regular.ttf
        - asset: assets/fonts/AbhayaLibre-Medium.ttf
          weight: 500
        - asset: assets/fonts/AbhayaLibre-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AbhayaLibre-Bold.ttf
          weight: 700
        - asset: assets/fonts/AbhayaLibre-ExtraBold.ttf
          weight: 800
flutter_intl:
  enabled: true
